version: "3.8"

services:
  api:
    build: .
    container_name: node_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/meubanco"
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: meubanco
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
